Updates running.org doc with latest instructions
EpicCash/epic pull request #86
Opened 2023-04-19 16:41 UTC by code-chronos

# Description

- Clear instructions on how to run the epic, epic-wallet binary file. 
- Moving foundation.json file and updates to epic-server.toml file.

2023-04-19 16:47 UTC, blacktyger commented on doc/running.org
> +2.  Unzip the downloaded epic wallet package. A binary file is available inside the unzipped paxkage.
typo `paxkage`

2023-04-19 16:48 UTC, blacktyger commented on doc/running.org
> +2.  Unzip the downloaded epic server package. A binary file and a foundation.json file are available inside the unzipped paxkage.
typo `paxkage`

2023-04-19 16:51 UTC, blacktyger requested changes
Fix the 2 typo's

2023-04-19 17:15 UTC, code-chronos commented on doc/running.org
> +2.  Unzip the downloaded epic wallet package. A binary file is available inside the unzipped paxkage.
Thanks. Updated

2023-04-20 20:05 UTC, blacktyger approved these changes

2023-04-22 08:13 UTC, johanneshahn approved these changes

2023-04-22 08:13 UTC, merged